wgpu error: Validation Error
Caused by:
    In Device::create_render_pipeline
    Internal error in VERTEX shader: Error compiling the shader "Naga validation: Type { handle: [22], name: \"TileData\", error: MemberOutOfBounds { index: 0, offset: 0, size: 64 } }"

thread 'main' panicked at 'Handling wgpu errors as fatal by default', /Users/benediktmandelkow/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/backend/direct.rs:1955:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ERROR gfx_backend_metal::command > Command buffer not released properly!
 ERROR gfx_backend_metal::command > Command buffer not released properly!