TODO fixup
    Finished dev [unoptimized + debuginfo] target(s) in 3.00s
     Running `target/debug/sailor`
[src/bin/drawing/weather/temperature.rs:212] &sampler = Sampler {
    context: Context {
        type: "Native",
    },
    id: (
        1,
        1,
        Metal,
    ),
}
 ERROR osm::vector_tile > Broken path.
 ERROR osm::vector_tile > Broken path.
 ERROR osm::vector_tile > Broken path.
 ERROR osm::vector_tile > Broken path.
 ERROR osm::vector_tile > Broken path.
 ERROR osm::vector_tile > Broken path.
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(1240, 1, Metal)>`
    In a set_scissor_rect command
    Invalid ScissorRect parameters

thread 'main' panicked at 'Handling wgpu errors as fatal by default', /Users/benediktmandelkow/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:1896:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace